version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - yum -y update --security
      - yum -y groupinstall "Development Tools"
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - export PLX_SDK_DIR=${PWD}
      - export PLX_CHIP=9054
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - make -C ${PLX_SDK_DIR}/PlxApi PLX_NO_CLEAR_SCREEN=1
      - test -e ${PLX_SDK_DIR}/PlxApi/Library/PlxApi.a || exit 1
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
